"""consolidated_schema_from_models

Revision ID: 793bd06278f0
Revises: 1c703144e570
Create Date: 2025-09-04 12:33:13.449958

"""


# revision identifiers, used by Alembic.
revision = '793bd06278f0'
down_revision = '1c703144e570'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
