"""
Centralized constant values for the AI Trading Bot project.
"""

DEFAULT_INITIAL_BALANCE: float = 1000  # Default starting balance in USD

# Prediction Engine Constants
DEFAULT_PREDICTION_HORIZONS = [1]  # Single horizon for MVP
DEFAULT_MIN_CONFIDENCE_THRESHOLD = 0.6
DEFAULT_MAX_PREDICTION_LATENCY = 0.1  # seconds
DEFAULT_MODEL_REGISTRY_PATH = "src/ml"
DEFAULT_ENABLE_SENTIMENT = False  # MVP: disabled
DEFAULT_ENABLE_MARKET_MICROSTRUCTURE = False  # MVP: disabled
DEFAULT_FEATURE_CACHE_TTL = 3600  # 1 hour
DEFAULT_MODEL_CACHE_TTL = 600  # seconds
DEFAULT_CONFIDENCE_SCALE_FACTOR = 10.0  # Scale factor for confidence calculation
DEFAULT_DIRECTION_THRESHOLD = 0.01  # 1% threshold for direction determination

# Feature Engineering Constants
DEFAULT_SEQUENCE_LENGTH = 120  # LSTM sequence length for technical features
DEFAULT_NORMALIZATION_WINDOW = 120  # Window for price normalization
DEFAULT_TECHNICAL_INDICATORS_ENABLED = True
DEFAULT_NAN_THRESHOLD = 0.5  # 50% threshold for NaN validation
DEFAULT_RSI_PERIOD = 14
DEFAULT_ATR_PERIOD = 14
DEFAULT_BOLLINGER_PERIOD = 20
DEFAULT_BOLLINGER_STD_DEV = 2.0
DEFAULT_MACD_FAST_PERIOD = 12
DEFAULT_MACD_SLOW_PERIOD = 26
DEFAULT_MACD_SIGNAL_PERIOD = 9
DEFAULT_MA_PERIODS = [20, 50, 200]

# Optimization Constants (Phase 10)
DEFAULT_OPTIMIZATION_ENABLED = True
DEFAULT_OPTIMIZATION_INTERVAL = 24  # hours
DEFAULT_PERFORMANCE_LOOKBACK_DAYS = 30
DEFAULT_MIN_TRADES_FOR_OPTIMIZATION = 50
DEFAULT_OPTIMIZATION_CONFIDENCE_THRESHOLD = 0.8
DEFAULT_MAX_PARAMETER_CHANGE = 0.2  # 20% max change per cycle
DEFAULT_OPTIMIZATION_COOLDOWN_HOURS = 6
DEFAULT_WIN_RATE_THRESHOLD = 0.45
DEFAULT_SHARPE_RATIO_THRESHOLD = 0.5
DEFAULT_DRAWDOWN_THRESHOLD = 0.15

# Model Outage Exit Policy (safe fallback when predictions are unavailable)
MODEL_OUTAGE_EXIT_ENABLED: bool = True
MODEL_OUTAGE_MAX_HOLD_SECONDS: int = 12 * 60 * 60  # 12 hours
MODEL_OUTAGE_BREAKEVEN_TRIGGER_PCT: float = 0.02  # Move stop to breakeven after +2%
MODEL_OUTAGE_TRAIL_ATR_MULTIPLIER: float = 1.0  # Trail by 1x ATR when in profit
MODEL_OUTAGE_TRAIL_MIN_PCT: float = 0.01  # Minimum trailing distance 1% if ATR unavailable
MODEL_OUTAGE_VOLATILITY_GUARD_MULTIPLIER: float = 2.5  # Exit/tighten if ATR spikes > 2.5x 20-bar median
