name: CI Lint

on:
  pull_request:
    branches: [ main, staging, develop ]

jobs:
  lint:
    if: ${{ false }}
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src:${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy bandit
      - name: Ruff
        run: ruff check .
      - name: Black (check)
        run: black --check .
      - name: Mypy
        run: mypy src
      - name: Bandit
        run: bandit -r src