name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 3 * * *'  # 03:00 UTC daily

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: trading_bot
          POSTGRES_PASSWORD: dev_password_123
          POSTGRES_DB: ai_trading_bot_test
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U trading_bot" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    # Built-in pip cache enabled above

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U trading_bot; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Run unit tests (parallel)
      env:
        DATABASE_URL: postgresql://trading_bot:dev_password_123@localhost:5432/ai_trading_bot_test
      run: |
        python tests/run_tests.py unit -q

# -----------------------
# Nightly integration job
# -----------------------
  integration:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: trading_bot
          POSTGRES_PASSWORD: dev_password_123
          POSTGRES_DB: ai_trading_bot_test
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U trading_bot" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U trading_bot; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Run integration tests (with DB & external providers)
      env:
        DATABASE_URL: postgresql://trading_bot:dev_password_123@localhost:5432/ai_trading_bot_test
        ENABLE_INTEGRATION_TESTS: '1'
      run: |
        python tests/run_tests.py integration -q
