name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    # Built-in pip cache enabled above

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests (parallel)
      run: |
        echo "Starting unit tests..."
        echo "Environment: $CI"
        echo "Python version: $(python --version)"
        echo "Available memory: $(free -h || echo 'free command not available')"
        echo "CPU cores: $(nproc || echo 'nproc not available')"
        python tests/run_tests.py unit -q
