name: CI Tests

on:
  push:
    branches: [ main, staging, develop ]
  pull_request:
    branches: [ main, staging, develop ]

jobs:
  test:
    strategy:
      matrix:
        split-index: [1, 2, 3, 4]
        python-version: [3.11]
      fail-fast: false  # Continue running other groups if one fails
    
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true
      PYTHONPATH: ${{ github.workspace }}/src:${{ github.workspace }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run split ${{ matrix.split-index }} of 4
      run: |
        echo "=== Starting split: ${{ matrix.split-index }}/4 ==="
        echo "PYTHONPATH=$PYTHONPATH"
        python -m pytest \
          -v \
          --tb=short \
          --timeout=300 \
          -m "not integration" \
          --splits 4 \
          --group ${{ matrix.split-index }} \
          --cov=src \
          --cov-report=term-missing \
          --cov-report=xml

  # Optional: Add a summary job that runs after all splits complete
  test-summary:
    needs: test
    runs-on: ubuntu-latest
    if: always()  # Run even if some test groups failed
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test Summary
      run: |
        echo "=== Test Matrix Summary ==="
        echo "All splits have completed."
        echo "Check individual split results above for details."
