name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      service_id:
        description: 'Override service ID (optional)'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway (production)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          SERVICE_ID: ${{ inputs.service_id }}
        run: |
          if [ -n "$SERVICE_ID" ]; then
            railway up --project $RAILWAY_PROJECT_ID --service $SERVICE_ID --environment production --detach
          else
            railway up --project $RAILWAY_PROJECT_ID --environment production --detach
          fi

      - name: Post deployment info
        run: echo "Deployment triggered for production environment."