name: PR Review Automation

on:
  pull_request_review:
    types: [submitted, edited]

jobs:
  cursor-agent-review:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    # Only run for bugbot or copilot reviews
    if: |
      github.event.review.user.login == 'bugbot' || 
      github.event.review.user.login == 'copilot' ||
      github.event.review.user.login == 'github-actions[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: Launch Cursor Background Agent
      run: |
        echo "=== Launching Cursor Background Agent for PR Review ==="
        echo "PR: ${{ github.event.pull_request.html_url }}"
        echo "Reviewer: ${{ github.event.review.user.login }}"
        echo "Review State: ${{ github.event.review.state }}"
        
        # Construct simple prompt with just the PR URL
        cat > prompt.txt << EOF
        A PR review has been submitted. Please analyze this PR and take appropriate action based on the reviewer's feedback.
        
        PR URL: ${{ github.event.pull_request.html_url }}
        Branch: ${{ github.event.pull_request.head.ref }}
        
        Use your knowledge of the project coding style, settings, architecture, known issues and other relevant information to verify the issues in this pull request and decide whether they should be fixed or not. If you do decide to fix them, leave a quick comment on the PR to say what you did and why. If you decide not to fix them, leave a comment to say why not. 1. Use the Github MCP server to access PR details and comments. 2. Checkout the branch ${{ github.event.pull_request.head.ref }} 3. Make any changes required. 3. Add and push your changes directly to ${{ github.event.pull_request.head.ref }}.
        EOF
        
        echo "=== Sending to Cursor Background Agent ==="
        
        # Launch Cursor background agent
        curl -X POST "https://api.cursor.com/v0/agents" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.CURSOR_API_KEY }}" \
          -d "{ \"prompt\": { \"text\": $(cat prompt.txt | jq -Rs .) }, \"source\": { \"repository\": \"${{ github.server_url }}/${{ github.repository }}\", \"ref\": \"${{ github.event.pull_request.head.ref }}\" } }"
        
        echo ""
        echo "=== Cursor Background Agent Launched ==="
        echo "The agent will analyze the PR review and take appropriate action."
        echo "Check the PR for any comments or changes made by the agent."
        
        # Cleanup temporary files
        rm -f prompt.txt
  
    - name: Log Review Details
      run: |
        echo "=== Review Summary ==="
        echo "PR: ${{ github.event.pull_request.html_url }}"
        echo "Reviewer: ${{ github.event.review.user.login }}"
        echo "State: ${{ github.event.review.state }}"
        echo "Submitted at: ${{ github.event.review.submitted_at }}"
        echo "Cursor agent launched successfully" 