name: CI

on:
  pull_request:
  push:
    branches: ["**"]

jobs:
  lint-type-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install ruff==0.5.0 black==24.4.2 mypy==1.10.0 bandit==1.7.9 types-requests || true

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (check only)
        run: black --check .

      - name: Mypy
        run: mypy --config-file mypy.ini src

      - name: Bandit
        run: bandit -c pyproject.toml -r src